#!/usr/bin/env python
"""Griffin launcher script."""

import os.path, sys, conf

here = os.path.dirname(__file__)

premises = ["jython.jar", "antlr-2.7.5.jar", "xercesImpl.jar", "junit.jar", 
            "xmlParserAPIs.jar"]
premisedir = "premises"

classpath = [os.path.join(here, premisedir, x) for x in premises]
classpath += [os.path.join(here, "Griffin.jar")]

cmd = "java -classpath '%s' backend.robin.Launcher" % \
	 conf.java_pathsep.join(classpath)


if __name__ == "__main__":
	os.system(cmd + " " + " ".join(sys.argv[1:]))
