
scribble.tar.gz: Makefile phase1 phase2 phase3 phase4 phase5
	tar zcf $@ $+

clean:
	rm -rf `find . -name "*~" -o -name "*.pyc"`
	rm -rf `find . -name "*.o" -o -name "*.so" -o -name 4robin.cc -o -name xml -o -name module.tag`
