#!/usr/bin/env python
"""Griffin launcher script."""

import os.path, sys, conf

here = os.path.dirname(__file__)

premises = ["jython.jar", "antlr-2.7.5.jar", "xercesImpl.jar", "junit.jar", 
            "xmlParserAPIs.jar"]
premisedir = "premises"

classpath = [os.path.join(here, premisedir, x) for x in premises]
classpath += [os.path.join(here, "Griffin.jar")]

doxpath = os.path.join(here, "build/dox-xml")
stpath = os.path.join(here, "src/griffin/modules/stl")

cmd = "java -Dgriffin.dox.path=%s -Dgriffin.st.path=%s -classpath '%s' backend.robin.Launcher" % \
	 (doxpath, stpath, conf.java_pathsep.join(classpath))


if __name__ == "__main__":
	os.system(cmd + " " + " ".join(sys.argv[1:]))
